apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: default 
  name: kafka 
spec:
  serviceName: "kafka"
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        component: kafka
    spec:
      terminationGracePeriodSeconds: 10
      #initContainers:
       # - name: init 
        #  image: alpine:latest
         # command:
          #  - /bin/sh
           # - -c
           # - "for i in $(seq -s ' ' 1 60); do if getent hosts zoo1:2181,zoo2:2181,zoo3:2181.default; then exit 0; fi; sleep 1; done; exit 1"
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest 
          command: ["/usr/local/bin/entrypoint.sh"]
          env:
            - name: ZOOKEEPER 
              value: "zoo1:2181,zoo2:2181,zoo3:2181"
            - name: DISCOVERY 
              value: zoo 
            - name: DATABASE 
              value: http://database-headless.database:8080/api/svc/db 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: runable
              mountPath: /usr/local/bin/entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
            - name: config
              mountPath: /tmp/server.properties
              subPath: server.properties
              readOnly: true
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: runable
          configMap:
            name: kafka-scripts 
            defaultMode: 0755
        - name: config 
          configMap:
            name: kafka-conf 
